### ISSUE TITLE
Compile runtime text code

### ISSUE THREAD

**Issue by swfly** [LuisaGroup/LuisaCompute#64]
Hello, we are trying to rebuild our renderer kernel with LuisaCompute. Previously we use node-based workflow to generate code text and let NVRTC JIT compile it to get kernels. Is there runtime code text compilation feature in LuisaCompute so we can achieve similar thing? I couldn't find it by searching the code. 
Thanks!

**Comment by swfly** [comment]
Hi thanks for the information. I first read your SIGGRAPH paper, and then I am here!
I understand LuisaCompute performs JIT compile at runtime, however what we are concerned about is whether it's possible to compile a kernel from a string (assume the content is source code written in LuisaCompute's DSL), which is procedurally generated. As far as I am aware, currently the Device::compile function only takes kernel objects. I guess there should be a way to generate kernel from string but don't know where it is. Of course LuisaCompute is fully capable for it, just wonder if this feature is already implemented.

**Comment by Mike-Leo-Smith** [comment]
Oh, I see :-)

This feature is not exposed, but should be easy to implement as it is what the backends actually do (example: the [`CUDACompiler::compile()`](https://github.com/LuisaGroup/LuisaCompute/blob/cc06371be8de2cd1d73a6ba131a18f1d829b3b18/src/backends/cuda/cuda_compiler.cpp#L17) method). I would like to help refactor this into a standalone method if you need it.

The tricky part would be making the source compatible with other parts of the DSL and runtime. For example, we would need certain mechanism to "reflect" the arguments and resource usages from the source string, so that the argument binding and command scheduling functionalities could work.

Another (possibly) useful approach is to support injections of "custom" kernel operations into the DSL as part of a kernel, by using a similar syntax to inline assembly. We think this might be a valid solution to easily extending the system and are planning the feature in the next version of LuisaCompute.

**Comment by swfly** [comment]
Hi yes seems both approaches would work. Previously we did pretty much similar with your second approach. Either way, we will first try a bit further with LuisaCompute and see what we really want. Maybe we can contribute a bit to this project too.

**Comment by Mike-Leo-Smith** [comment]
Thanks! And looking forward to your good news!

**Comment by Mike-Leo-Smith** [comment]
We have (experimentally) introduced a simple "native include" feature recently, which allows users to include code segments  written in the native shading language and call the imported `ExternalCallable`s. Example is here: [test_native_include](https://github.com/LuisaGroup/LuisaCompute/blob/next/src/tests/test_native_include.cpp).

The method still has some limitations, e.g., resources are not supported and no type checks are performed. We will try to improve it in the future.
